title = "Bookliu"
languageCode = "zh-CN"
baseURL = "https://kdefan.net"
timeZone = "Asia/Shanghai"
theme = "paper"
copyright = ""
googleAnalytics = "G-5PZT6MYW8X"
disqusShortname = "kdefan"
pygmentsUseClasses = true
pygmentsCodefences = true

uglyURLs = true
summaryLength = 10

# directories
archetypeDir = "archetypes"
assetDir = "assets"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
themesDir = "themes"

# https://gohugo.io/getting-started/configuration/#disablekinds
disableKinds = []
# https://gohugo.io/getting-started/configuration/#enablerobotstxt
enableRobotsTXT = false

# https://gohugo.io/getting-started/configuration/#paginatepath
paginate = 10
paginatePath = "page"

[data]
  [data.author]
    image = "/avatar.jpg"
    name = "yaxin"

[params]
  # params for theme ghostwriter
  dateFormat = "2006-01-02"
  rss = true
  headline = "飞天大面包"
  description = "为梦想添砖加瓦"
  mainSections = ["posts"]
  intro = false

[markup]
  defaultMarkdownHandler = "goldmark"

  # [markup.highlight]
  #   codeFences = true
  #   guessSyntax = false
  #   lineNos = false
  #   lineNoStart = 1
  #   lineNumbersInTable = true
  #   noClasses = true
  #   tabWidth = 2
  #   style = "monokai"

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

    [markup.goldmark.renderer]
      unsafe = true

[privacy.disqus]
  disable = false

[privacy.googleAnalytics]
  anonymizeIP = true
  respectDoNotTrack = false
  useSessionStorage = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "归档"
    identifier = "blog"
    weight = 2
    url = "/posts.html"
  [[menu.main]]
    name = "关于"
    identifier = "about"
    weight = 3
    url = "/about.html"
  # [[menu.main]]
  #   name = "标签"
  #   identifier = "tags"
  #   weight = 4
  #   url = "/tags.html"

# https://gohugo.io/content-management/taxonomies/#configure-taxonomies
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# https://gohugo.io/content-management/urls/#tokens
[permalinks]
  posts = "/posts/:slug"
  tags = '/tags/:title'

# https://gohugo.io/templates/sitemap-template/#configuration
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
