title = "飞天大面包"
languageCode = "zh-CN"
baseURL = "https://kdefan.net"
timeZone = "Asia/Shanghai"
theme = "hugo-winston-theme"

uglyURLs = true

archetypeDir = "archetypes"
assetDir = "assets"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
themesDir = "themes"

# https://gohugo.io/getting-started/configuration/#disablekinds
disableKinds = []
# https://gohugo.io/getting-started/configuration/#enablerobotstxt
enableRobotsTXT = false

copyright = ""

# https://gohugo.io/getting-started/configuration/#paginatepath
paginate = 10
paginatePath = "page"

[data]
  [data.author]
    image = "/avatar.jpg"
    name = "yaxin"

[params]
  AuthorName = "yaxin"
  GitHubUser = "norduo"
  Subtitle = "为梦想添砖加瓦"
  # params for theme hugo-winston-theme
  google_analytics_id = "G-5PZT6MYW8X"
  twitter_handle = ""
  showAuthorOnHomepage =false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = false
  addFrame = true
  plausible_analytics_domain = "kdefan.net"
  highlightColor = '#00a4ff'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#7b16ff"
  enableGoogleFonts = true
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "归档"
    identifier = "blog"
    weight = 2
    url = "/posts.html"
  [[menu.main]]
    name = "关于"
    identifier = "about"
    weight = 3
    url = "/about.html"
  # [[menu.main]]
  #   name = "标签"
  #   identifier = "tags"
  #   weight = 4
  #   url = "/tags.html"

# https://gohugo.io/content-management/taxonomies/#configure-taxonomies
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

# https://gohugo.io/content-management/urls/#tokens
[permalinks]
  posts = "/posts/:filename"
  tags = '/tags/:title'

# https://gohugo.io/templates/sitemap-template/#configuration
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
